AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
#    Layers:
#      # Our own layer that we are going to build
#      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs16.x
    MemorySize: 128
    Timeout: 100


Resources:
  LogItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata: # Manual build process
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/logItem.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: seltzers
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST


  GetInventoryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata: # Manual build process
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/getInventory.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: seltzers
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

#  RuntimeDependenciesLayer:
#    Type: AWS::Serverless::LayerVersion
#    Metadata:
#      BuildMethod: makefile # This does the trick
#    Properties:
#      Description: Runtime dependencies for Lambdas
#      ContentUri: ./
#      CompatibleRuntimes:
#        - nodejs16.x
#      RetentionPolicy: Retain

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Test stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Test/"
